import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body>
      <nav>
        <div className="flex items-center justify-between w-full">
        <p className="text-hilight">Portfolio Website</p>
        <div className="flex gap-8">
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
        </div>
        </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
